services:
  - type: web
    name: macugnagabooking
    runtime: python
    plan: starter
    buildCommand: ""
    startCommand: python serve.py
    envVars:
      - key: PLANYO_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.8"